# Generated by Django 5.2.7 on 2025-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("roll_no", models.CharField(max_length=20, unique=True)),
                ("class_name", models.CharField(max_length=20)),
                ("section", models.CharField(blank=True, max_length=5)),
                ("date_of_birth", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                ("joined_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
